# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sock
email: jdavis7901@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Sell alot of socks
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://socks.com" # the base hostname & protocol for your site
twitter_username: J_Dav22
github_username:  Trainwreck1026

# Build settings
markdown: kramdown
